/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "./tests/0.include.check" instead.
 */

#include <check.h>

#include "../src/brick_game/tetris/tetris.h"
#include "../src/brick_game/tetris/backend.h"
#include "../src/brick_game/tetris/fsm.h"
#include "../src/brick_game/tetris/bonus.h"



START_TEST(createField_test_1)
{

TetField_t * field = createField();
ck_assert_ptr_nonnull(field);
freeField(field);
}
END_TEST

START_TEST(createFigure_test_1)
{

TetFigure_t * figure = createRandomFigure(0);
ck_assert_ptr_nonnull(figure);

freeFigure(figure);




}
END_TEST

START_TEST(createGame_test_1)
{

TetGame_t * game = createGame();
ck_assert_ptr_nonnull(game);
freeGame(game);


}
END_TEST

START_TEST(moveDown_test_succes)
{
TetFigure_t * figure = createRandomFigure(0);
figure->y = 1;
int y_end = 2;
moveFigureDown(figure);
ck_assert_int_eq(y_end, figure->y);
freeFigure(figure);


}
END_TEST

START_TEST(moveLeft_test_succes)
{
TetFigure_t * figure = createRandomFigure(0);
figure->x = 5;
int x_end = 4;
moveFigureLeft(figure);
ck_assert_int_eq(x_end, figure->x);
freeFigure(figure);


}
END_TEST

START_TEST(moveRight_test_succes)
{
TetFigure_t * figure = createRandomFigure(0);
figure->x = 5;
int x_end = 6;
moveFigureRight(figure);
ck_assert_int_eq(x_end, figure->x);
freeFigure(figure);


}
END_TEST

START_TEST(moveUp_test_succes)
{
TetFigure_t * figure = createRandomFigure(0);
figure->y = 5;
int y_end = 4;
moveFigureUp(figure);
ck_assert_int_eq(y_end, figure->y);
freeFigure(figure);

}
END_TEST

START_TEST(userAction_test_KEY_UP)
{
TetGame_t * game = initGame();
game->figure->y = 0;
game->figure->x = 0;
int ch = KEY_UP;
userAction(game,ch);
ck_assert_int_eq(game->action , Up);
freeGame(game);


}
END_TEST

START_TEST(userAction_test_KEY_DOWN)
{
TetGame_t * game = initGame();
game->figure->y = 0;
game->figure->x = 0;
int ch = KEY_DOWN;
userAction(game,ch);
ck_assert_int_eq(game->action , Down);
freeGame(game);


}
END_TEST

START_TEST(userAction_test_KEY_LEFT)
{
TetGame_t * game = initGame();
game->figure->y = 0;
game->figure->x = 0;
int ch = KEY_LEFT;
userAction(game,ch);
ck_assert_int_eq(game->action , Left);
freeGame(game);


}
END_TEST

START_TEST(userAction_test_KEY_RIGHT)
{
TetGame_t * game = initGame();
game->figure->y = 0;
game->figure->x = 0;
int ch = KEY_RIGHT;
userAction(game,ch);
ck_assert_int_eq(game->action , Right);
freeGame(game);


}
END_TEST

START_TEST(userAction_test_q)
{
TetGame_t * game = initGame();
game->figure->y = 0;
game->figure->x = 0;
int ch =  'q';
userAction(game,ch);
ck_assert_int_eq( game->gameStatus , Terminate);
freeGame(game);



}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("field");
    TCase *tc1_1 = tcase_create("field");
    Suite *s2 = suite_create("figure");
    TCase *tc2_1 = tcase_create("figure");
    Suite *s3 = suite_create("game");
    TCase *tc3_1 = tcase_create("game");
    Suite *s4 = suite_create("moveFigure");
    TCase *tc4_1 = tcase_create("moveFigure");
    Suite *s5 = suite_create("userAction");
    TCase *tc5_1 = tcase_create("userAction");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, createField_test_1);
    suite_add_tcase(s2, tc2_1);
    tcase_add_test(tc2_1, createFigure_test_1);
    suite_add_tcase(s3, tc3_1);
    tcase_add_test(tc3_1, createGame_test_1);
    suite_add_tcase(s4, tc4_1);
    tcase_add_test(tc4_1, moveDown_test_succes);
    tcase_add_test(tc4_1, moveLeft_test_succes);
    tcase_add_test(tc4_1, moveRight_test_succes);
    tcase_add_test(tc4_1, moveUp_test_succes);
    suite_add_tcase(s5, tc5_1);
    tcase_add_test(tc5_1, userAction_test_KEY_UP);
    tcase_add_test(tc5_1, userAction_test_KEY_DOWN);
    tcase_add_test(tc5_1, userAction_test_KEY_LEFT);
    tcase_add_test(tc5_1, userAction_test_KEY_RIGHT);
    tcase_add_test(tc5_1, userAction_test_q);

    srunner_add_suite(sr, s2);
    srunner_add_suite(sr, s3);
    srunner_add_suite(sr, s4);
    srunner_add_suite(sr, s5);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
